// 脚本化假 LLM：以 Vercel AI SDK 的 LanguageModelV2 接口实现的离线 provider（零在线调用，Issue #5）。
// 经 customProvider 注册为 `scripted` 系列模型，由 streamText / generateText 消费——模型交互整体走 AI SDK
// provider 抽象，后续替换真实 provider 时只换 provider 工厂、不动工作流。
// #9 扩展：① 三档模型（scripted-fast/standard/deep，对应三档推理强度，供路由断言）；
// ② 质检模型 scripted-quality（reviewer 工位结构化质检分，返回 code-quality-check JSON）；
// ③ 超限剧本 limit（工具调用无休止，触发 max_tool_calls/max_turns 上限验证优雅收尾）；
// ④ 调用记录 records（modelId + maxOutputTokens + prompt 角色，断言路由与档位上限随动）。

import { customProvider } from 'ai'
import type { LanguageModelV2, LanguageModelV2CallOptions, LanguageModelV2StreamPart } from '@ai-sdk/provider'

export type LlmScript =
  // 成功剧本：一轮文本 + writeFile 工具 + 收尾文本（契约成功路径）
  | 'success'
  // 模型层失败剧本：一进流式即抛错（工作流 catch → failed 终态）
  | 'error'
  // 图片配额剧本：一轮内并行多次图片搜索（第 2 次触发配额拒绝）
  | 'images'
  // 质检失败-重试后通过：第 1 次质检 isValid:false（触发 RETRY），第 2 次起 isValid:true（重试后通过）
  | 'quality-fail-then-pass'
  // 质检永远失败：每次质检 isValid:false（重试耗尽 → failed 终态）
  | 'quality-fail-always'
  // 超限剧本：工具调用无休止（触发 max_tool_calls / max_turns 上限，验证优雅收尾）
  | 'limit'

// 单次模型调用记录（测试断言：路由到哪个模型 id、收到什么上限、prompt 是否含工具结果）
export interface ScriptedCallRecord {
  modelId: string
  maxOutputTokens: number | undefined
  hasToolResult: boolean
}

// 用户消息 → 页面内容（评审内容即 ai_response 增量文本的拼接）
// 产物含应用内导览组件（onboarding tour，Issue #8 验收「生成产物包含应用内导览组件」）。
export function buildPageContent(message: string): string {
  const title = message.trim() || 'generated page'
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  #onboarding-tour{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.5)}
  .tour-panel{background:#fff;border-radius:8px;padding:24px;max-width:320px;box-shadow:0 4px 20px rgba(0,0,0,.2)}
  .tour-actions{display:flex;justify-content:space-between;margin-top:16px}
  button{cursor:pointer;border:none;border-radius:4px;padding:6px 12px}
  .tour-next{background:#4f6ef7;color:#fff}
  .tour-skip{background:transparent;color:#666}
</style>
</head>
<body>
<h1>${title}</h1>
<p>generated by scripted fake llm</p>
<!-- 应用内导览组件：新用户引导，覆盖关键区块，可主动关闭 -->
<div id="onboarding-tour" role="dialog" aria-label="新手引导">
  <div class="tour-panel" data-step="1"><p>欢迎使用 ${title}，这是首页概览。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">下一步</button></div></div>
  <div class="tour-panel" data-step="2"><p>这是核心功能入口，点击即可开始使用。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">完成</button></div></div>
</div>
<script>
  // 导览组件逻辑：步骤切换与关闭（应用内组件，非独立文档）
  (function () {
    var tour = document.getElementById('onboarding-tour');
    var panels = tour.querySelectorAll('.tour-panel');
    var idx = 0;
    function show(i) { panels.forEach(function (p, k) { p.style.display = k === i ? 'block' : 'none'; }); }
    function close() { tour.style.display = 'none'; }
    show(0);
    panels.forEach(function (p) {
      p.querySelector('.tour-next').addEventListener('click', function () {
        idx += 1;
        if (idx >= panels.length) close(); else show(idx);
      });
    });
    tour.querySelectorAll('.tour-skip').forEach(function (b) { b.addEventListener('click', close); });
  })();
</script>
</body>
</html>
`
}

// 工具调用 id（契约要求 tool_request 与对应 tool_executed 同 id；假模型每轮固定调用）
const WRITE_FILE_TOOL_CALL_ID = 'write-file-1'
const IMAGE_SEARCH_TOOL_CALL_IDS = ['image-search-1', 'image-search-2']

// 把预置 part 序列封成 ReadableStream（SDK 按序消费）
function streamFromParts(parts: LanguageModelV2StreamPart[]): ReadableStream<LanguageModelV2StreamPart> {
  return new ReadableStream<LanguageModelV2StreamPart>({
    start(controller) {
      for (const part of parts) controller.enqueue(part)
      controller.close()
    },
  })
}

// 假模型公共行为：prompt 工具结果判定与最近用户文本提取
function hasToolResult(options: LanguageModelV2CallOptions): boolean {
  return options.prompt.some((message) => message.role === 'tool')
}

function lastUserText(options: LanguageModelV2CallOptions): string {
  for (let i = options.prompt.length - 1; i >= 0; i--) {
    const message = options.prompt[i]
    if (message?.role === 'user') {
      const text = message.content
        .filter((part) => part.type === 'text')
        .map((part) => part.text)
        .join('')
      if (text) return text
    }
  }
  return ''
}

// codegen 假模型（三档共用同一实现，modelId 区分路由）
class ScriptedLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId: string
  readonly supportedUrls = {}

  constructor(
    private readonly script: LlmScript,
    modelId: string,
    private readonly records: ScriptedCallRecord[],
  ) {
    this.modelId = modelId
  }

  // 非流式路径（当前工作流 codegen 只走 streamText；doGenerate 供接口完整性与收尾调用）
  async doGenerate(options: LanguageModelV2CallOptions) {
    this.record(options)
    // 收尾调用（优雅收尾注入收尾指令后）：输出用户可见的完整交代
    const wrapUp = this.script === 'limit' ? '\n已达本次生成硬上限，以上为已生成的页面内容。\n' : '\n页面已写入 index.html\n'
    return {
      content: [{ type: 'text' as const, text: buildPageContent(lastUserText(options)) + wrapUp }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      warnings: [],
    }
  }

  private record(options: LanguageModelV2CallOptions): void {
    this.records.push({
      modelId: this.modelId,
      maxOutputTokens: options.maxOutputTokens,
      hasToolResult: hasToolResult(options),
    })
  }

  async doStream(options: LanguageModelV2CallOptions) {
    this.record(options)
    if (this.script === 'error') {
      // error 剧本：模型一进流式即失败（工作流 catch 后走 failed 终态，error 后不再发业务事件）
      throw new Error('假 LLM 剧本故意失败')
    }
    if (this.script === 'limit') {
      // 超限剧本：工具调用无休止（每次都不带工具结果则继续调用工具，永不自然收尾）——
      // 直到工作流侧 max_tool_calls / max_turns 上限截断（stopWhen）后注入收尾指令走 doGenerate
      if (!hasToolResult(options)) {
        const parts: LanguageModelV2StreamPart[] = [
          { type: 'text-start', id: 'page' },
          { type: 'text-delta', id: 'page', delta: '正在生成页面' },
          { type: 'text-end', id: 'page' },
          {
            type: 'tool-call',
            toolCallId: `limit-${this.records.length}`,
            toolName: 'writeFile',
            input: JSON.stringify({ relativeFilePath: 'index.html', content: buildPageContent(lastUserText(options)) }),
          },
          { type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } },
        ]
        return { stream: streamFromParts(parts) }
      }
      // 带工具结果仍继续调用（无休止循环，由 stopWhen 截断）
      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'again' },
        { type: 'text-delta', id: 'again', delta: '继续生成' },
        { type: 'text-end', id: 'again' },
        {
          type: 'tool-call',
          toolCallId: `limit-${this.records.length}`,
          toolName: 'writeFile',
          input: JSON.stringify({ relativeFilePath: 'index.html', content: buildPageContent(lastUserText(options)) }),
        },
        { type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } },
      ]
      return { stream: streamFromParts(parts) }
    }
    const content = buildPageContent(lastUserText(options))
    if (!hasToolResult(options)) {
      // 第一轮：流式页面内容（供 ai_response）+ 工具调用（供 tool_request/tool_executed）
      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'page' },
        // 拆两块模拟增量流式，契约定 ai_response 按增量块推送
        { type: 'text-delta', id: 'page', delta: content.slice(0, 32) },
        { type: 'text-delta', id: 'page', delta: content.slice(32) },
        { type: 'text-end', id: 'page' },
      ]
      if (this.script === 'images') {
        // images 剧本：一轮内并行多次图片搜索——第 2 次触发配额拒绝（每 run 4 张，第 1 次取满）
        for (const id of IMAGE_SEARCH_TOOL_CALL_IDS) {
          parts.push({
            type: 'tool-call',
            toolCallId: id,
            toolName: 'searchContentImages',
            input: JSON.stringify({ query: `产品图 ${id}` }),
          })
        }
      } else {
        parts.push({
          type: 'tool-call',
          toolCallId: WRITE_FILE_TOOL_CALL_ID,
          toolName: 'writeFile',
          // arguments 为 JSON 字符串（契约 tool_request.arguments 语义）；
          // writeFile 参数与 Java ProjectFileWriteTool 对齐：relativeFilePath + content（#8 审查整改 A1）
          input: JSON.stringify({ relativeFilePath: 'index.html', content }),
        })
      }
      parts.push({ type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 } })
      return { stream: streamFromParts(parts) }
    }
    // 第二轮（工具结果已回喂）
    const tailText = this.script === 'images' ? '\n图片资源已收集（配额内）\n' : '\n页面已写入 index.html\n'
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'tail' },
      { type: 'text-delta', id: 'tail', delta: tailText },
      { type: 'text-end', id: 'tail' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 3, outputTokens: 1, totalTokens: 4 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}

// 质检假模型（reviewer 工位）：按剧本返回 code-quality-check JSON（isValid/errors/suggestions）。
// quality-fail-then-pass：第 1 次质检失败、第 2 次起通过（有界重试后通过剧本）；
// quality-fail-always：永远失败（重试耗尽 → failed）。
class QualityLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId = 'scripted-quality'
  readonly supportedUrls = {}

  // 质检调用次数（区分 then-pass 剧本的第 1 次与后续）
  private calls = 0

  constructor(
    private readonly script: LlmScript,
    private readonly records: ScriptedCallRecord[],
  ) {}

  private isValidNow(): boolean {
    this.calls += 1
    if (this.script === 'quality-fail-always') return false
    if (this.script === 'quality-fail-then-pass') return this.calls >= 2
    return true
  }

  private buildQualityJson(): string {
    const isValid = this.isValidNow()
    const result = isValid
      ? { isValid: true, errors: [], suggestions: [] }
      : {
          isValid: false,
          errors: ['生成页面缺少必要的视觉还原（模拟质检失败）'],
          suggestions: ['按已确认线框调整页面布局与区块结构'],
        }
    return JSON.stringify(result)
  }

  async doGenerate(options: LanguageModelV2CallOptions) {
    this.records.push({ modelId: this.modelId, maxOutputTokens: options.maxOutputTokens, hasToolResult: hasToolResult(options) })
    const text = this.buildQualityJson()
    return {
      content: [{ type: 'text' as const, text }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 10, outputTokens: 10, totalTokens: 20 },
      warnings: [],
    }
  }

  async doStream(options: LanguageModelV2CallOptions) {
    // 质检走 generateText（doGenerate）；doStream 为接口完整性
    this.records.push({ modelId: this.modelId, maxOutputTokens: options.maxOutputTokens, hasToolResult: hasToolResult(options) })
    const text = this.buildQualityJson()
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'quality' },
      { type: 'text-delta', id: 'quality', delta: text },
      { type: 'text-end', id: 'quality' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 10, outputTokens: 10, totalTokens: 20 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}

// 工厂：按剧本创建脚本化 provider；注册三档 codegen 模型 + 质检模型。
// records 由 provider 持有，测试经 provider.records 断言路由与档位上限。
export function createScriptedLlm(script: LlmScript = 'success') {
  const records: ScriptedCallRecord[] = []
  const provider = customProvider({
    languageModels: {
      'scripted-fast': new ScriptedLanguageModel(script, 'scripted-fast', records),
      'scripted-standard': new ScriptedLanguageModel(script, 'scripted-standard', records),
      'scripted-deep': new ScriptedLanguageModel(script, 'scripted-deep', records),
      'scripted-quality': new QualityLanguageModel(script, records),
    },
  })
  return Object.assign(provider, { records })
}

export type ScriptedLlmProvider = ReturnType<typeof createScriptedLlm>
