







import { customProvider } from 'ai'
import type { LanguageModelV2, LanguageModelV2CallOptions, LanguageModelV2StreamPart } from '@ai-sdk/provider'

export type LlmScript =

  | 'success'
  | 'error'
  | 'images'
  | 'multi-file'
  | 'quality-fail-then-pass'
  | 'quality-fail-always'
  | 'limit'
  | 'limit-length'


export interface ScriptedCallRecord {
  modelId: string
  maxOutputTokens: number | undefined
  hasToolResult: boolean
  system?: string
}




export class ScriptedModelError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ModelInvocationError'
  }
}




export function buildPageContent(message: string): string {
  const title = message.trim() || 'generated page'
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  #onboarding-tour{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.5)}
  .tour-panel{background:#fff;border-radius:8px;padding:24px;max-width:320px;box-shadow:0 4px 20px rgba(0,0,0,.2)}
  .tour-actions{display:flex;justify-content:space-between;margin-top:16px}
  button{cursor:pointer;border:none;border-radius:4px;padding:6px 12px}
  .tour-next{background:#4f6ef7;color:#fff}
  .tour-skip{background:transparent;color:#666}
  section.page{border:1px solid #eee;padding:16px;margin:8px 0}
  .mock-list{list-style:none;padding:0}
  .mock-list li{padding:6px 8px;border-bottom:1px dashed #e5e5e5}
  .mock-form{display:flex;gap:8px;margin-top:10px}
  .mock-form input{flex:1;padding:6px 8px;border:1px solid #ddd;border-radius:4px}
  .mock-form button{background:#4f6ef7;color:#fff}
  .mock-status{font-size:12px;color:#999;margin-top:6px}
</style>
<script>
  (function () {
    var FIXTURES = {
      'GET /api/items': { code: 0, data: [
        { id: 'mock-1', title: '示例条目一', desc: 'mock fixture 数据' },
        { id: 'mock-2', title: '示例条目二', desc: '预览态可演示' },
        { id: 'mock-3', title: '示例条目三', desc: '表单提交后追加' }
      ] },
      'POST /api/items': { code: 0, data: { id: 'mock-new', created: true } }
    };
    function matchFixture(method, url) {
      var path = String(url).replace(/^https?:\\/\\/[^/]+/, '');
      return FIXTURES[method + ' ' + path] || FIXTURES[method + ' ' + path.split('?')[0]];
    }
    function fixtureResponse(matched, requestBody) {
      if (requestBody && matched === FIXTURES['POST /api/items']) {
        try {
          var parsed = JSON.parse(requestBody);
          return { code: 0, data: { id: 'mock-new', created: true, echo: parsed } };
        } catch (e) { }
      }
      return matched;
    }
    var originalFetch = window.fetch;
    window.fetch = function (input, init) {
      var url = typeof input === 'string' ? input : (input && input.url) || '';
      var method = ((init && init.method) || (input && input.method) || 'GET').toUpperCase();
      var matched = matchFixture(method, url);
      if (!matched || !originalFetch) {
        return originalFetch ? originalFetch.apply(window, arguments) : Promise.reject(new Error('fetch blocked'));
      }
      return Promise.resolve(new Response(JSON.stringify(fixtureResponse(matched, init && init.body)), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    };
    var OriginalXHR = window.XMLHttpRequest;
    function MockXHR() {
      var xhr = new OriginalXHR();
      var mocked = null;
      var originalOpen = xhr.open;
      xhr.open = function (method, url) {
        mocked = matchFixture(String(method).toUpperCase(), url);
        return originalOpen.apply(xhr, arguments);
      };
      xhr.send = function (body) {
        if (!mocked) return originalOpen.apply(xhr, arguments);
        Object.defineProperty(xhr, 'status', { value: 200 });
        Object.defineProperty(xhr, 'readyState', { value: 4 });
        Object.defineProperty(xhr, 'responseText', { value: JSON.stringify(fixtureResponse(mocked, body)) });
        if (typeof xhr.onreadystatechange === 'function') xhr.onreadystatechange();
        if (typeof xhr.onload === 'function') xhr.onload();
      };
      return xhr;
    }
    MockXHR.prototype = OriginalXHR.prototype;
    window.XMLHttpRequest = MockXHR;
  })();
</script>
</head>
<body>
<h1>${title}</h1>
<p>generated by scripted fake llm</p>
<!-- 页面区段骨架（#9 视觉 diff 基准对比对象）：单页骨架 page-0，供默认视觉 diff 门禁比对 -->
<section class="page" id="page-0"><h2>首页</h2><p>${title} 的内容概览</p>
  <ul class="mock-list" id="mock-items"></ul>
  <form class="mock-form" id="mock-form">
    <input type="text" id="mock-input" placeholder="输入新条目标题" />
    <button type="submit">添加</button>
  </form>
  <p class="mock-status" id="mock-status">列表经 mock 拦截层加载</p>
</section>
<!-- 应用内导览组件：新用户引导，覆盖关键区块，可主动关闭 -->
<div id="onboarding-tour" role="dialog" aria-label="新手引导">
  <div class="tour-panel" data-step="1"><p>欢迎使用 ${title}，这是首页概览。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">下一步</button></div></div>
  <div class="tour-panel" data-step="2"><p>这是核心功能入口，点击即可开始使用。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">完成</button></div></div>
</div>
<script>
  (function () {
    var tour = document.getElementById('onboarding-tour');
    var panels = tour.querySelectorAll('.tour-panel');
    var idx = 0;
    function show(i) { panels.forEach(function (p, k) { p.style.display = k === i ? 'block' : 'none'; }); }
    function close() { tour.style.display = 'none'; }
    show(0);
    panels.forEach(function (p) {
      p.querySelector('.tour-next').addEventListener('click', function () {
        idx += 1;
        if (idx >= panels.length) close(); else show(idx);
      });
    });
    tour.querySelectorAll('.tour-skip').forEach(function (b) { b.addEventListener('click', close); });
  })();
  (function () {
    var list = document.getElementById('mock-items');
    var status = document.getElementById('mock-status');
    function renderItem(item) {
      var li = document.createElement('li');
      li.textContent = item.title + (item.desc ? ' —— ' + item.desc : '');
      list.appendChild(li);
    }
    fetch('/api/items').then(function (res) { return res.json(); }).then(function (json) {
      (json.data || []).forEach(renderItem);
      status.textContent = '已加载 ' + (json.data || []).length + ' 条 mock 数据';
    }).catch(function () {
      status.textContent = '列表加载失败';
    });
    document.getElementById('mock-form').addEventListener('submit', function (event) {
      event.preventDefault();
      var input = document.getElementById('mock-input');
      var title = input.value.trim();
      if (!title) return;
      fetch('/api/items', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: title })
      }).then(function (res) { return res.json(); }).then(function (json) {
        renderItem({ title: title, desc: json.data && json.data.created ? '已创建（mock 回显）' : '' });
        input.value = '';
        status.textContent = '提交成功：' + title;
      }).catch(function () {
        status.textContent = '提交失败';
      });
    });
  })();
</script>
</body>
</html>
`
}


const WRITE_FILE_TOOL_CALL_ID = 'write-file-1'
const IMAGE_SEARCH_TOOL_CALL_IDS = ['image-search-1', 'image-search-2']

const MULTI_FILE_CONTENTS: Array<{ relativeFilePath: string; content: string }> = [
  {
    relativeFilePath: 'index.html',
    content: '<!DOCTYPE html>\n<html>\n<head><title>多文件页面</title><link rel="stylesheet" href="style.css"></head>\n<body>\n<section id="page-1"><div id="app">多文件应用</div></section>\n<script src="script.js"></script>\n</body>\n</html>',
  },
  {
    relativeFilePath: 'style.css',
    content: 'body { margin: 0; }\n#app { color: red; }',
  },
  {
    relativeFilePath: 'script.js',
    content: "const app = document.getElementById('app');\napp.addEventListener('click', () => alert('ok'));",
  },
]


function streamFromParts(parts: LanguageModelV2StreamPart[]): ReadableStream<LanguageModelV2StreamPart> {
  return new ReadableStream<LanguageModelV2StreamPart>({
    start(controller) {
      for (const part of parts) controller.enqueue(part)
      controller.close()
    },
  })
}


function hasToolResult(options: LanguageModelV2CallOptions): boolean {
  return options.prompt.some((message) => message.role === 'tool')
}

function lastUserText(options: LanguageModelV2CallOptions): string {
  for (let i = options.prompt.length - 1; i >= 0; i--) {
    const message = options.prompt[i]
    if (message?.role === 'user') {
      const text = message.content
        .filter((part) => part.type === 'text')
        .map((part) => part.text)
        .join('')
      if (text) return text
    }
  }
  return ''
}


class ScriptedLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId: string
  readonly supportedUrls = {}

  constructor(
    private readonly script: LlmScript,
    modelId: string,
    private readonly records: ScriptedCallRecord[],
  ) {
    this.modelId = modelId
  }


  async doGenerate(options: LanguageModelV2CallOptions) {
    this.record(options)

    const wrapUp = this.script === 'limit' || this.script === 'limit-length'
      ? '\n已达本次生成硬上限，以上为已生成的页面内容。\n'
      : '\n页面已写入 index.html\n'
    return {
      content: [{ type: 'text' as const, text: buildPageContent(lastUserText(options)) + wrapUp }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      warnings: [],
    }
  }

  private record(options: LanguageModelV2CallOptions): void {
    this.records.push({
      modelId: this.modelId,
      maxOutputTokens: options.maxOutputTokens,
      hasToolResult: hasToolResult(options),
      system: options.prompt ? JSON.stringify(options.prompt) : undefined,
    })
  }

  async doStream(options: LanguageModelV2CallOptions) {
    this.record(options)
    if (this.script === 'error') {

      throw new ScriptedModelError('假 LLM 剧本故意失败')
    }
    if (this.script === 'limit' || this.script === 'limit-length') {





      if (!hasToolResult(options) || this.script === 'limit-length') {
        const parts: LanguageModelV2StreamPart[] = [
          { type: 'text-start', id: 'page' },
          { type: 'text-delta', id: 'page', delta: '正在生成页面' },
          { type: 'text-end', id: 'page' },
        ]
        if (this.script === 'limit-length') {

          parts.push({ type: 'finish', finishReason: 'length', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } })
        } else {
          parts.push(
            {
              type: 'tool-call',
              toolCallId: `limit-${this.records.length}`,
              toolName: 'writeFile',
              input: JSON.stringify({ relativeFilePath: 'index.html', content: buildPageContent(lastUserText(options)) }),
            },
            { type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } },
          )
        }
        return { stream: streamFromParts(parts) }
      }

      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'again' },
        { type: 'text-delta', id: 'again', delta: '继续生成' },
        { type: 'text-end', id: 'again' },
        {
          type: 'tool-call',
          toolCallId: `limit-${this.records.length}`,
          toolName: 'writeFile',
          input: JSON.stringify({ relativeFilePath: 'index.html', content: buildPageContent(lastUserText(options)) }),
        },
        { type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } },
      ]
      return { stream: streamFromParts(parts) }
    }
    const content = buildPageContent(lastUserText(options))
    if (!hasToolResult(options)) {

      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'page' },

        { type: 'text-delta', id: 'page', delta: content.slice(0, 32) },
        { type: 'text-delta', id: 'page', delta: content.slice(32) },
        { type: 'text-end', id: 'page' },
      ]
      if (this.script === 'images') {

        for (const id of IMAGE_SEARCH_TOOL_CALL_IDS) {
          parts.push({
            type: 'tool-call',
            toolCallId: id,
            toolName: 'searchContentImages',
            input: JSON.stringify({ query: `产品图 ${id}` }),
          })
        }
      } else if (this.script === 'multi-file') {

        for (const [index, file] of MULTI_FILE_CONTENTS.entries()) {
          parts.push({
            type: 'tool-call',
            toolCallId: `write-file-${index + 1}`,
            toolName: 'writeFile',
            input: JSON.stringify(file),
          })
        }
      } else {
        parts.push({
          type: 'tool-call',
          toolCallId: WRITE_FILE_TOOL_CALL_ID,
          toolName: 'writeFile',


          input: JSON.stringify({ relativeFilePath: 'index.html', content }),
        })
      }
      parts.push({ type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 } })
      return { stream: streamFromParts(parts) }
    }

    const tailText = this.script === 'images'
      ? '\n图片资源已收集（配额内）\n'
      : this.script === 'multi-file'
        ? '\n多文件已写入工作区\n'
        : '\n页面已写入 index.html\n'
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'tail' },
      { type: 'text-delta', id: 'tail', delta: tailText },
      { type: 'text-end', id: 'tail' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 3, outputTokens: 1, totalTokens: 4 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}






class QualityLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId = 'scripted-quality'
  readonly supportedUrls = {}


  private calls = 0

  constructor(
    private readonly script: LlmScript,
    private readonly records: ScriptedCallRecord[],
  ) {}

  private isValidNow(): boolean {
    this.calls += 1
    if (this.script === 'quality-fail-always') return false
    if (this.script === 'quality-fail-then-pass') return this.calls >= 2
    return true
  }

  private buildQualityJson(): string {
    const isValid = this.isValidNow()
    const result = isValid
      ? { isValid: true, errors: [], suggestions: [] }
      : {
          isValid: false,
          errors: ['生成页面缺少必要的视觉还原（模拟质检失败）'],
          suggestions: ['按已确认线框调整页面布局与区块结构'],
        }
    return JSON.stringify(result)
  }

  async doGenerate(options: LanguageModelV2CallOptions) {
    this.records.push({ modelId: this.modelId, maxOutputTokens: options.maxOutputTokens, hasToolResult: hasToolResult(options) })
    const text = this.buildQualityJson()
    return {
      content: [{ type: 'text' as const, text }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 10, outputTokens: 10, totalTokens: 20 },
      warnings: [],
    }
  }

  async doStream(options: LanguageModelV2CallOptions) {

    this.records.push({ modelId: this.modelId, maxOutputTokens: options.maxOutputTokens, hasToolResult: hasToolResult(options) })
    const text = this.buildQualityJson()
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'quality' },
      { type: 'text-delta', id: 'quality', delta: text },
      { type: 'text-end', id: 'quality' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 10, outputTokens: 10, totalTokens: 20 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}



export function createScriptedLlm(script: LlmScript = 'success') {
  const records: ScriptedCallRecord[] = []
  const provider = customProvider({
    languageModels: {
      'scripted-fast': new ScriptedLanguageModel(script, 'scripted-fast', records),
      'scripted-standard': new ScriptedLanguageModel(script, 'scripted-standard', records),
      'scripted-deep': new ScriptedLanguageModel(script, 'scripted-deep', records),
      'scripted-quality': new QualityLanguageModel(script, records),
    },
  })
  return Object.assign(provider, { records })
}




export type LlmProvider = Pick<ReturnType<typeof customProvider>, 'languageModel'>
