// 脚本化假 LLM：以 Vercel AI SDK 的 LanguageModelV2 接口实现的离线 provider（零在线调用，Issue #5）。
// 经 customProvider 注册为 `scripted` 模型，由 streamText 消费——模型交互（文本流 + 工具循环）整体走 AI SDK provider 抽象，
// 后续替换真实 provider（OpenAI/DeepSeek 等）时只换 provider 工厂、不动工作流。
import { customProvider } from 'ai'
import type { LanguageModelV2, LanguageModelV2CallOptions, LanguageModelV2StreamPart } from '@ai-sdk/provider'

export type LlmScript = 'success' | 'error'

// 假模型从用户消息确定性合成页面内容（评审内容即 ai_response 增量文本的拼接）
export function buildPageContent(message: string): string {
  const title = message.trim() || 'generated page'
  return `<!DOCTYPE html>\n<html>\n<body>\n<h1>${title}</h1>\n<p>generated by scripted fake llm</p>\n</body>\n</html>\n`
}

// 工具调用 id（契约要求 tool_request 与对应 tool_executed 同 id；假模型每轮固定一个调用）
const WRITE_FILE_TOOL_CALL_ID = 'write-file-1'

// 把预置 part 序列封成 ReadableStream（SDK 按序消费）
function streamFromParts(parts: LanguageModelV2StreamPart[]): ReadableStream<LanguageModelV2StreamPart> {
  return new ReadableStream<LanguageModelV2StreamPart>({
    start(controller) {
      for (const part of parts) controller.enqueue(part)
      controller.close()
    },
  })
}

class ScriptedLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId: string
  readonly supportedUrls = {}

  constructor(private readonly script: LlmScript) {
    this.modelId = `scripted-${script}`
  }

  // 当前 prompt 是否已带工具结果（工具循环的第二轮调用）
  private hasToolResult(options: LanguageModelV2CallOptions): boolean {
    return options.prompt.some((message) => message.role === 'tool')
  }

  // 取最近一条用户文本（页面内容合成的输入）
  private lastUserText(options: LanguageModelV2CallOptions): string {
    for (let i = options.prompt.length - 1; i >= 0; i--) {
      const message = options.prompt[i]
      if (message?.role === 'user') {
        const text = message.content
          .filter((part) => part.type === 'text')
          .map((part) => part.text)
          .join('')
        if (text) return text
      }
    }
    return ''
  }

  // 非流式路径（当前工作流只走 streamText；doGenerate 为接口完整性实现）
  async doGenerate(options: LanguageModelV2CallOptions) {
    const text = buildPageContent(this.lastUserText(options))
    return {
      content: [{ type: 'text' as const, text }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      warnings: [],
    }
  }

  async doStream(options: LanguageModelV2CallOptions) {
    if (this.script === 'error') {
      // error 剧本：模型一进流式即失败（工作流 catch 后走 failed 终态，error 后不再发业务事件）
      throw new Error('假 LLM 剧本故意失败')
    }
    const content = buildPageContent(this.lastUserText(options))
    if (!this.hasToolResult(options)) {
      // 第一轮：流式页面内容（供 ai_response）+ writeFile 工具调用（供 tool_request/tool_executed）
      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'page' },
        // 拆块模拟增量流式
        { type: 'text-delta', id: 'page', delta: content.slice(0, 32) },
        { type: 'text-delta', id: 'page', delta: content.slice(32) },
        { type: 'text-end', id: 'page' },
        {
          type: 'tool-call',
          toolCallId: WRITE_FILE_TOOL_CALL_ID,
          toolName: 'writeFile',
          // arguments 为 JSON 字符串（契约 tool_request.arguments 语义）
          input: JSON.stringify({ relativeFilePath: 'index.html' }),
        },
        { type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 } },
      ]
      return { stream: streamFromParts(parts) }
    }
    // 第二轮：工具已执行，收尾文本（仍可流式）
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'tail' },
      { type: 'text-delta', id: 'tail', delta: '\n页面已写入 index.html\n' },
      { type: 'text-end', id: 'tail' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 3, outputTokens: 1, totalTokens: 4 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}

// 工厂：按剧本创建脚本化 provider；模型 id 固定 `scripted`
export function createScriptedLlm(script: LlmScript = 'success') {
  return customProvider({ languageModels: { scripted: new ScriptedLanguageModel(script) } })
}

export type ScriptedLlmProvider = ReturnType<typeof createScriptedLlm>
