// 脚本化假 LLM：以 Vercel AI SDK 的 LanguageModelV2 接口实现的离线 provider（零在线调用，Issue #5）。
// 经 customProvider 注册为 `scripted` 模型，由 streamText 消费——模型交互（文本流 + 工具循环）整体走 AI SDK provider 抽象，
// 后续替换真实 provider（OpenAI/DeepSeek 等）时只换 provider 工厂、不动工作流。
import { customProvider } from 'ai'
import type { LanguageModelV2, LanguageModelV2CallOptions, LanguageModelV2StreamPart } from '@ai-sdk/provider'

export type LlmScript = 'success' | 'error' | 'images'

// 假模型从用户消息确定性合成页面内容（评审内容即 ai_response 增量文本的拼接）。
// 产物含应用内导览组件（onboarding tour，Issue #8 验收「生成产物包含应用内导览组件」）：
// 固定定位引导浮层 + 步骤切换 + 跳过，纯原生 JS 驱动，随应用打开、可被主动关闭。
export function buildPageContent(message: string): string {
  const title = message.trim() || 'generated page'
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  #onboarding-tour{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.5)}
  .tour-panel{background:#fff;border-radius:8px;padding:24px;max-width:320px;box-shadow:0 4px 20px rgba(0,0,0,.2)}
  .tour-actions{display:flex;justify-content:space-between;margin-top:16px}
  button{cursor:pointer;border:none;border-radius:4px;padding:6px 12px}
  .tour-next{background:#4f6ef7;color:#fff}
  .tour-skip{background:transparent;color:#666}
</style>
</head>
<body>
<h1>${title}</h1>
<p>generated by scripted fake llm</p>
<!-- 应用内导览组件：新用户引导，覆盖关键区块，可主动关闭 -->
<div id="onboarding-tour" role="dialog" aria-label="新手引导">
  <div class="tour-panel" data-step="1"><p>欢迎使用 ${title}，这是首页概览。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">下一步</button></div></div>
  <div class="tour-panel" data-step="2"><p>这是核心功能入口，点击即可开始使用。</p><div class="tour-actions"><button class="tour-skip">跳过</button><button class="tour-next">完成</button></div></div>
</div>
<script>
  // 导览组件逻辑：步骤切换与关闭（应用内组件，非独立文档）
  (function () {
    var tour = document.getElementById('onboarding-tour');
    var panels = tour.querySelectorAll('.tour-panel');
    var idx = 0;
    function show(i) { panels.forEach(function (p, k) { p.style.display = k === i ? 'block' : 'none'; }); }
    function close() { tour.style.display = 'none'; }
    show(0);
    panels.forEach(function (p) {
      p.querySelector('.tour-next').addEventListener('click', function () {
        idx += 1;
        if (idx >= panels.length) close(); else show(idx);
      });
    });
    tour.querySelectorAll('.tour-skip').forEach(function (b) { b.addEventListener('click', close); });
  })();
</script>
</body>
</html>
`
}

// 工具调用 id（契约要求 tool_request 与对应 tool_executed 同 id；假模型每轮固定调用）
const WRITE_FILE_TOOL_CALL_ID = 'write-file-1'
const IMAGE_SEARCH_TOOL_CALL_IDS = ['image-search-1', 'image-search-2']

// 把预置 part 序列封成 ReadableStream（SDK 按序消费）
function streamFromParts(parts: LanguageModelV2StreamPart[]): ReadableStream<LanguageModelV2StreamPart> {
  return new ReadableStream<LanguageModelV2StreamPart>({
    start(controller) {
      for (const part of parts) controller.enqueue(part)
      controller.close()
    },
  })
}

class ScriptedLanguageModel implements LanguageModelV2 {
  readonly specificationVersion = 'v2' as const
  readonly provider = 'scripted'
  readonly modelId: string
  readonly supportedUrls = {}

  constructor(private readonly script: LlmScript) {
    this.modelId = `scripted-${script}`
  }

  // 当前 prompt 是否已带工具结果（工具循环的第二轮调用）
  private hasToolResult(options: LanguageModelV2CallOptions): boolean {
    return options.prompt.some((message) => message.role === 'tool')
  }

  // 取最近一条用户文本（页面内容合成的输入）
  private lastUserText(options: LanguageModelV2CallOptions): string {
    for (let i = options.prompt.length - 1; i >= 0; i--) {
      const message = options.prompt[i]
      if (message?.role === 'user') {
        const text = message.content
          .filter((part) => part.type === 'text')
          .map((part) => part.text)
          .join('')
        if (text) return text
      }
    }
    return ''
  }

  // 非流式路径（当前工作流只走 streamText；doGenerate 为接口完整性实现）
  async doGenerate(options: LanguageModelV2CallOptions) {
    const text = buildPageContent(this.lastUserText(options))
    return {
      content: [{ type: 'text' as const, text }],
      finishReason: 'stop' as const,
      usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
      warnings: [],
    }
  }

  async doStream(options: LanguageModelV2CallOptions) {
    if (this.script === 'error') {
      // error 剧本：模型一进流式即失败（工作流 catch 后走 failed 终态，error 后不再发业务事件）
      throw new Error('假 LLM 剧本故意失败')
    }
    const content = buildPageContent(this.lastUserText(options))
    if (!this.hasToolResult(options)) {
      // 第一轮：流式页面内容（供 ai_response）+ 工具调用（供 tool_request/tool_executed）
      const parts: LanguageModelV2StreamPart[] = [
        { type: 'text-start', id: 'page' },
        // 拆两块模拟增量流式，契约定 ai_response 按增量块推送
        { type: 'text-delta', id: 'page', delta: content.slice(0, 32) },
        { type: 'text-delta', id: 'page', delta: content.slice(32) },
        { type: 'text-end', id: 'page' },
      ]
      if (this.script === 'images') {
        // images 剧本：一轮内并行多次图片搜索——第 2 次触发配额拒绝（每 run 4 张，第 1 次取满）
        for (const id of IMAGE_SEARCH_TOOL_CALL_IDS) {
          parts.push({
            type: 'tool-call',
            toolCallId: id,
            toolName: 'searchContentImages',
            input: JSON.stringify({ query: `产品图 ${id}` }),
          })
        }
      } else {
        parts.push({
          type: 'tool-call',
          toolCallId: WRITE_FILE_TOOL_CALL_ID,
          toolName: 'writeFile',
          // arguments 为 JSON 字符串（契约 tool_request.arguments 语义）
          input: JSON.stringify({ relativeFilePath: 'index.html' }),
        })
      }
      parts.push({ type: 'finish', finishReason: 'tool-calls', usage: { inputTokens: 2, outputTokens: 3, totalTokens: 5 } })
      return { stream: streamFromParts(parts) }
    }
    // 第二轮（工具结果已回喂）
    const tailText = this.script === 'images' ? '\n图片资源已收集（配额内）\n' : '\n页面已写入 index.html\n'
    const parts: LanguageModelV2StreamPart[] = [
      { type: 'text-start', id: 'tail' },
      { type: 'text-delta', id: 'tail', delta: tailText },
      { type: 'text-end', id: 'tail' },
      { type: 'finish', finishReason: 'stop', usage: { inputTokens: 3, outputTokens: 1, totalTokens: 4 } },
    ]
    return { stream: streamFromParts(parts) }
  }
}

// 工厂：按剧本创建脚本化 provider；模型 id 固定 `scripted`
export function createScriptedLlm(script: LlmScript = 'success') {
  return customProvider({ languageModels: { scripted: new ScriptedLanguageModel(script) } })
}

export type ScriptedLlmProvider = ReturnType<typeof createScriptedLlm>
