spring:
  # 项目名称
  application:
    name: paimeng-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paimeng_ai_code_mother
    username: root
    password: root
  profiles:
    active: local

# 端口 根路径
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        # 设置 sessionId 过期时间（30天），不设置的话前端不会将 sessionId 保存到硬盘，关闭浏览器后登录态丢失
        max-age: 2592000s

# springdoc
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zdan.paimengaicodemother.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn